"""create plugin installs table

Revision ID: 17fd4231d59d
Revises: 090ed2f96676
Create Date: 2026-07-24 18:05:56.221970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17fd4231d59d'
down_revision: Union[str, Sequence[str], None] = '090ed2f96676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_installs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plugin_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_id', 'user_id', name='uq_plugin_install')
    )
    op.create_index(op.f('ix_plugin_installs_id'), 'plugin_installs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plugin_installs_id'), table_name='plugin_installs')
    op.drop_table('plugin_installs')
    # ### end Alembic commands ###
